language: node_js
node_js:
  - "0.11"
install:
  - "npm install -g typescript"
script:
  - 'tsc -t "ES5" --out "/build/LZMA.js" "src/lzma/LZMA.ts" --sourcemap'
  - 'tsc -t "ES5" --out "/build/LZMAWorker.js" "src/lzma/LZMAWorker.ts" --sourcemap'